name: pay_or_save
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.19+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # hexcolor: ^2.0.0
  video_player: ^2.1.0
  chewie: ^1.0.0
  provider: ^6.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.1
  firebase_messaging:
  firebase_storage: ^10.0.3
  google_sign_in: ^5.2.0
  shared_preferences: ^2.0.7
  flutter_launcher_icons: ^0.9.2
  cloud_firestore: ^3.3.0
  file_picker: ^4.0.2
  google_fonts: ^3.0.1
  charts_flutter: ^0.12.0
  flare_flutter: ^3.0.2
  percent_indicator:
  youtube_player_flutter: ^8.0.0
  image_picker: ^0.8.4
  loading_animations: ^2.1.0
  firebase_core: ^1.6.0
  animated_text_kit: ^4.1.1
  http: ^0.13.0
  transparent_image: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^3.0.4
  english_words: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  flutter_facebook_auth: ^4.4.0+1
  url_launcher: ^6.0.18
  font_awesome_flutter: ^10.1.0
  google_mobile_ads: ^1.1.0
  social_share: ^2.2.1
  cloud_functions: ^3.3.7
  purchases_flutter: ^6.30.2
  crypto: ^3.0.0
  convert: ^3.1.0
  flutter_screenutil: ^5.7.0
  logger: any
  flutter_easyloading: any
  confetti: any
  pointycastle: ^3.7.3
  asn1lib: 
  basic_utils: ^5.4.2
  flutter_local_notifications:

dependency_overrides:
  firebase_core_platform_interface: 4.5.1
  purchases_flutter: ^4.12.0
  # kotlin: 1.8.0
  # kotlin-stdlib: 1.8.0
  # kotlin-stdlib-jdk7: 1.8.0
  # kotlin-stdlib-jdk8: 1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/posmob.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/ebay.png
    - assets/ebay.svg
    - assets/category.json
    - assets/db.json
    - assets/animation/
    - assets/images/
    - assets/images/Video1.png
    - assets/images/Social/
    - assets/images/Accounts/
    - assets/images/anim/
    - assets/images/buttons/
    - assets/images/gifs/
    - assets/images/Headers/
    - assets/images/iconsGoals/
    - assets/images/new/
    - assets/images/new/videoassets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
